version: "3"
services:
  wordpress:
    # replace username/repo:tag with your name and image details
    image: wordpress
    links:
      - mysql:mysql
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
      ports:
      - "8000:80"
    networks:
      - webnet
  mysql:
    image: mysql
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
    networks:
      - webnet
    environment:
      MYSQL_ROOT_PASSWORD: password
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
  
networks:
webnet:
