---
-  hosts: localhost
  tasks:
      - name: Create file
        file:
            path: /tmp/yallo
            state: touch
 
- hosts: localhost
  sudo: yes
  tasks:
      - name: Create user
        user:
            name: mario
            shell: /bin/zsh
 
      - name: Install zlib  
        yum:
            name: zlib
            state: latest