---
- name: Install nginx
  hosts: localhost
  become: true

  tasks:
  - name: Add epel-release repo
    yum:
      name: epel-release
      state: present

  - name: Install httpd
    yum:
      name: httpd
      state: present

  - name: Start NGiNX
    service:
      name: httpd
      state: started